client_config_backend: settings
client_config:
  client_id: {GOOGLE CLIEND ID}
  client_secret: {GOOGLE CLIENT SECRET}

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive
